#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUpload
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FileDB")]
	public partial class FileDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public FileDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FileDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public FileDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FileDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FileDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public FileDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Link_IsValid")]
		public int Link_IsValid([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Guid", DbType="UniqueIdentifier")] System.Nullable<System.Guid> guid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="Int")] ref System.Nullable<int> status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), guid, status);
			status = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Register_Insert")]
		public int Register_Insert(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="VarChar(30)")] string name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(50)")] string gender, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Job", DbType="VarChar(50)")] string job, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="VarChar(15)")] string mobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(50)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="VarChar(MAX)")] string address, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Resume", DbType="VarBinary(MAX)")] System.Data.Linq.Binary resume, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Xth", DbType="VarBinary(MAX)")] System.Data.Linq.Binary xth, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="XIIth", DbType="VarBinary(MAX)")] System.Data.Linq.Binary xIIth, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Graduation", DbType="VarBinary(MAX)")] System.Data.Linq.Binary graduation, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdharCard", DbType="VarBinary(MAX)")] System.Data.Linq.Binary adharCard, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PanCard", DbType="VarBinary(MAX)")] System.Data.Linq.Binary panCard, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhotoType", DbType="NVarChar(50)")] string photoType, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhotoName", DbType="VarChar(50)")] string photoName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhotoBinary", DbType="VarBinary(MAX)")] System.Data.Linq.Binary photoBinary, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACNum", DbType="VarChar(50)")] string aCNum, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IFSCCode", DbType="VarChar(50)")] string iFSCCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Passbook", DbType="VarBinary(MAX)")] System.Data.Linq.Binary passbook, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Count", DbType="Int")] ref System.Nullable<int> count)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, gender, job, mobile, email, address, resume, xth, xIIth, graduation, adharCard, panCard, photoType, photoName, photoBinary, aCNum, iFSCCode, passbook, count);
			count = ((System.Nullable<int>)(result.GetParameterValue(18)));
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
